### ISSUE TITLE
Move social media from gist to README

### ISSUE THREAD

**Issue by sheharyaar** [sheharyaar/iit-kgp-network#18]
- work in progress

**Comment by proffapt** [comment]
After the commit [Moving Contribution guidelines and Contributors list to README.md](https://github.com/sheharyaar/iit-kgp-network/commit/614d1a9bb2808ce6cdbaaef1f19c0db0918b292b) I guess we have the position to add the gist into readme; but it should have a non-technical counterpart too, this one has some technical aspects, not much tho; so much confusion..

**Comment by sheharyaar** [comment]
Yeah, create a PR for the contrib. The gist can be done in another branch.

**Comment by proffapt** [comment]
> Yeah, create a PR for the contrib. The gist can be done in another branch.

Ig everything looks fine now and is in track.

**Comment by sheharyaar** [comment]
@proffapt please checkout branch `feature-social-media` for a starting point

**Comment by proffapt** [comment]
> @proffapt please checkout branch `feature-social-media` for a starting point

that's exactly what I was doing right now

**Comment by sheharyaar** [comment]
Cool
