### ISSUE TITLE
Re-organising the repository structure

### ISSUE THREAD

**Issue by proffapt** [sheharyaar/iit-kgp-network#19]
- [NOTES.md](https://github.com/sheharyaar/iit-kgp-network/blob/main/NOTES.md) and [vpnNotes.md](https://github.com/sheharyaar/iit-kgp-network/blob/main/vpnNotes.md) can be organised in one folder named as todo or notes.
This won't have any issues with other part of documentation as these are not referred anywhere else.
- putting pdfs like [vpn-expressvpnAudit.pdf](https://github.com/sheharyaar/iit-kgp-network/blob/main/vpn-expressvpnAudit.pdf) in folder named pdfs or docs.

Suggest changes if needed, will push the changes accordingly.

**Comment by sheharyaar** [comment]
I would suggest to delete the notes as it was created by me for my reference. I will move the pdf to docs
