### ISSUE TITLE
UDP and TCP packet drops

### ISSUE THREAD

**Issue by sheharyaar** [sheharyaar/iit-kgp-network#2]
There is a strange behavior with the firewall dropping TCP and UDP packets. After hosting a server using netcat on cloud (both EC2 and DigitalOcean),

I tested TCP using `netcat` and `telnet`. Both connected successfully. For UDP testing, I used netcat only. The servers were created on even reserved category ports which are not in use.

The strange behaviour I noticed was that, both TCP and UDP connections were dropped on both netcat and telnet exactly after `6 data transfers` ( the 7th couldn't 
 be processed by the server and the conenction was reset ). 

More information from important tools like `wireshark` or `tcpdump` would be helpful. 
Information can be gathered about this behaviour by changing the size of the messages and forcing fragmentation. Tinkering with MTU size can also provide some insight.

**Comment by sheharyaar** [comment]
Another weird things happens. When connected with `-v` option : `nc -v <IP> <port>` , netcat displays `XXXXX` ( 5 Xs) and then accepts only a single data transfer and then exits. So still a total of 6 data transfers.

**Comment by FadedCoder** [comment]
We can try checking port wise. Maybe some ports have been allowed, like 3389 is for Windows UDP?
