### ISSUE TITLE
Platform for Discussion

### ISSUE THREAD

**Issue by proffapt** [sheharyaar/iit-kgp-network#20]
Enable the discussion area for this repository, idk how exactly to refer it.. thus attaching an image to clarify..
This will provide a good platform for ordered discussion regarding multiple topics right here on github.

<img width="1252" alt="image" src="https://user-images.githubusercontent.com/86282911/185253463-81d777ae-e51b-4d62-a830-22f52cf3bd4b.png">

**Comment by sheharyaar** [comment]
Done
