### ISSUE TITLE
Version of "ticks"

### ISSUE THREAD

**Issue by proffapt** [sheharyaar/iit-kgp-network#23]
Umm.. why to use ✔️, why not ✅
The first one has almost same shade as that of background of github.. and that decreases the readability to some extent..
looks for both versions are attached below:

<img width="214" alt="image" src="https://user-images.githubusercontent.com/86282911/186350504-5e2b56c1-5ffc-45ce-9ad3-ce7a7ed84a4c.png" align="right">

<img width="201" alt="image" src="https://user-images.githubusercontent.com/86282911/186350583-cce332f0-3d8a-4033-bfa1-d049abeefcf1.png" align="left">

**Comment by sheharyaar** [comment]
LGTM
