### ISSUE TITLE
Petition to update status of netlify link

### ISSUE THREAD

**Issue by proffapt** [sheharyaar/iit-kgp-network#26]
Since many things were added to the repo, and many changes were made.. we should update the status of netlify version of this doc too

- [x] Update it

**Comment by proffapt** [comment]
Facche coming soon, will be good for them

**Comment by proffapt** [comment]
And as i am sharing the repo, they are generally clicking this

**Comment by sheharyaar** [comment]
updated the netlify book, please check and close the issue.

**Comment by proffapt** [comment]
> updated the netlify book, please check and close the issue.

On my way!

**Comment by proffapt** [comment]
https://github.com/sheharyaar/iit-kgp-network-book/pull/1

Rest seems good
