### ISSUE TITLE
Update ExpressVPN results

### ISSUE THREAD

**Issue by proffapt** [sheharyaar/iit-kgp-network#28]
- [ ] Update ExpressVPN results

https://github.com/sheharyaar/iit-kgp-network/blob/d7250aae2eb8dd0270a033d05c52d0f02e6533d1/README_technical.md?plain=1#L445

**Comment by proffapt** [comment]
@yureien you too use ExpressVPN right?
Would be nice if you also help

**Comment by Yureien** [comment]
Alright sure.

**Comment by sheharyaar** [comment]
Can we close this? @proffapt

**Comment by proffapt** [comment]
> Can we close this? @proffapt 

I can't update express vpn results as i don't have it's subscription.

**Comment by sheharyaar** [comment]
Let's close this up then. It's fine if the benches are outdated
