### ISSUE TITLE
UDP VPNs

### ISSUE THREAD

**Issue by harshkhandeparkar** [sheharyaar/iit-kgp-network#30]
As suggested by [this blog](https://anjaygoel.github.io/posts/IIT-KGP-An-update-on-VPNs/), UDP port `19302` (among others) is not blocked and is used by Gmeet on Campus Network.

I tried running OpenVPN on Azure with UDP protocol and port `19302` and here are the results

Linux, Ethernet 1000 Mbps
Azure Central India Server [Pune]

1) Without VPN
fast.com[servers: Block EP Sector V, Saltlake, IN  |  Patna, IN  |  Nagpur, IN]: 640 Mbps down, 250 Mbps up
speedtest.net[server: Airtel, KGP, IN]: 550 Mbps down, 52 Mbps up
speedtest.net[server: Gazon Comm, Pune, IN]: 540 Mbps dpwm, 135 Mbps up

2) With VPN
fast.com[servers: Ciudad de Buenos Aires, AR  |  Barranquilla, CO]: 8 Mbps down, 78 Mbps up (unreliable, chooses servers outside the country)
speedtest.net[server: Gazon Comm, Pune, IN]: 135 Mbps down, 140 Mbps up

Windows, Ethernet 1000 Mbps
Azure Central India Server [Pune]

Valorant: 60ms ping, 2-5ms jitter, ~0% packet loss

**Comment by sheharyaar** [comment]
Closing this as this doesn't work anymore
