### ISSUE TITLE
Can't connect to VPN hosted on Azure when on LAN.

### ISSUE THREAD

**Issue by Inteleks** [sheharyaar/iit-kgp-network#39]
It started yesterday but it works fine when we connect to to it over WiFi.

**Comment by sheharyaar** [comment]
If you are getting this error since yesterday, then it's something related to CIC, they are changing some things. It should be fine over a few days. Currently, I am out of campus so I can't debug or find a fix.

**Comment by sheharyaar** [comment]
I will debug once I reach campus after the weekend

**Comment by Inteleks** [comment]
Sure thing,

**Comment by Inteleks** [comment]
Just updating, it doesn't work on WiFi now also 🥲

**Comment by proffapt** [comment]
This will be resolved, will pursue CIC regarding this.

**Comment by Inteleks** [comment]
Any updates on this? Has CIC just straight-up blocked VPNs in general?

**Comment by sheharyaar** [comment]
Sorry, no update yet. There is negotiation going on with the CIC. Please wait a couple more days

**Comment by proffapt** [comment]
This place is not convenient to carry on the discussion. Prefer joining (MetaKGP Slack)[https://bit.ly/metakgp-slack]. And in that join `#kgp-network` channel.
